skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
simple_amm = "DhMBsKqY7iuu96xMjxPccZQ4wxiuqjXY1SXGUXxaprjv"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
