// SPDX-License-Identifier: MIT
pragma solidity 0.8.36;

import {Test, console} from "forge-std/Test.sol";
import {Groth16Verifier} from "../src/Verifier.sol";

contract OnChainVerificationTest is Test {
    Groth16Verifier verifier;

    // Real proof values generated from:
    // snarkjs zkey export soliditycalldata public.json proof.json

    uint256[2] pA = [
        0x1a84289b56cab95a3bee4d8528cdd6ee71ea9fa659845152a31f06c455a3b2eb,
        0x05355b8919b4a0d99b1e05af736f429da2fb302b1919c3ae659e0af10216f083
    ];

    uint256[2][2] pB = [
        [
            0x20ea1ff1bcdc1b312d989838d6254fd1a8f84b086d47407d5ee4e4fc9a3cb471,
            0x0b58e0640ebe389a6e67ead3e13c288d4286365db7fda58ac56d2dfd7c74f6ac
        ],
        [
            0x1beb7f590fe06ea4378eba35871779a549b3ec411f3eb08732e9195563c73445,
            0x2d913576ab29fd5de85985267a0c8c889bb7d87696f070052f34c3539d7525c1
        ]
    ];

    uint256[2] pC = [
        0x1d43a0da059da082e6081294313068bfd7134fb862f80894bd029a002c07f686,
        0x1db56415cb51ee6888d1f7d730f6971ecbf8ec8c25adbaedc4557b5706ab8bb3
    ];

    uint256[1] publicSignals = [uint256(42)];

    function setUp() public {
        verifier = new Groth16Verifier();
    }

    // The real proof generated by the correct multiplier circuit
    // must verify successfully on-chain.
    function testFix_RealProofVerifiesOnChain() public view {
        bool result = verifier.verifyProof(pA, pB, pC, publicSignals);

        assertTrue(result);
    }

    // The same proof must fail when the public output is changed
    // from the real value 42 to 41.
    function testExploit_TamperedPublicSignalFailsVerification() public view {
        uint256[1] memory tamperedSignals = [uint256(41)];

        bool result = verifier.verifyProof(pA, pB, pC, tamperedSignals);

        assertFalse(result);
    }

    // Measure the real gas cost of successful Groth16 verification.
    function testFix_OnChainVerificationHasARealFixedGasCost() public {
        uint256 gasBefore = gasleft();

        verifier.verifyProof(pA, pB, pC, publicSignals);

        uint256 verifyGas = gasBefore - gasleft();

        console.log("verifyProof gas cost:", verifyGas);

        assertLt(verifyGas, 300_000);
    }
}
