skip_local_validator = false

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
config_program = "BR9JoeTRjCmtNJMnaa76uExjcvQbX9yMgPy3cgwWcGt8"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"


[scripts]
test = "NODE_OPTIONS='--import tsx' npx mocha -t 1000000 tests/config-program.ts"

[hooks]
