skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault_anchor = "2wSvvqUyuh7pgWwnAyRumXiZc5Y7jQhYGCYBB34s9HF6"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
