skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
overflow_vault = "8eMb1hAdTdfkzELvq7rsAjUp7Re4M335Qy8xuvreqTaQ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
