skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
instant_unstake_pool = "C1UUig4375m6ReDbrjeJQkGJw4Jayhn3dnhJuRu7jnTu"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
