skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
simple_lst = "DoFF3AB2mSTQrWQQiNRMPkuqd9EFjHNyghDw4BGys8U1"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
