[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.36"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
